import { UserContextProvider } from "@/context/userContext"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <UserContextProvider>
        <body>{children}</body>
      </UserContextProvider>
    </html>
  )
}
